package com.dsfa.platform.service.core.web.test.lsf.nc.bqgl.model;

import com.dsfa.platform.service.core.web.test.lsf.nc.bqgl.model.base.BaseBqgl;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(
		tableName = "test_lsf_nc_bqgl",
		pkName = "test_lsf_nc_bqgl_id"
)
public class Bqgl extends BaseBqgl<Bqgl> {
	public static final Bqgl dao = new Bqgl().dao();

	public Bqgl() {
	}
}

