package com.dsfa.platform.service.core.web.test.lsf.nc.szgl.model.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSzglBdxx<M extends BaseSzglBdxx<M>> extends DsfaBaseModel<M> implements IBean {

	public M setTestLsfNcSzglBdxxId(java.lang.String testLsfNcSzglBdxxId) {
		set("test_lsf_nc_szgl_bdxx_id", testLsfNcSzglBdxxId);
		return (M)this;
	}
	
	public java.lang.String getTestLsfNcSzglBdxxId() {
		return getStr("test_lsf_nc_szgl_bdxx_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setTestLsfNcSzglId(java.lang.String testLsfNcSzglId) {
		set("test_lsf_nc_szgl_id", testLsfNcSzglId);
		return (M)this;
	}
	
	public java.lang.String getTestLsfNcSzglId() {
		return getStr("test_lsf_nc_szgl_id");
	}
	
	public M setZcValue(java.lang.String zcValue) {
		set("zc_value", zcValue);
		return (M)this;
	}
	
	public java.lang.String getZcValue() {
		return getStr("zc_value");
	}
	
	public M setZcText(java.lang.String zcText) {
		set("zc_text", zcText);
		return (M)this;
	}
	
	public java.lang.String getZcText() {
		return getStr("zc_text");
	}
	
	public M setGzdw(java.lang.String gzdw) {
		set("gzdw", gzdw);
		return (M)this;
	}
	
	public java.lang.String getGzdw() {
		return getStr("gzdw");
	}
	
	public M setZw(java.lang.String zw) {
		set("zw", zw);
		return (M)this;
	}
	
	public java.lang.String getZw() {
		return getStr("zw");
	}
	
	public M setTimeOperate(java.lang.String timeOperate) {
		set("time_operate", timeOperate);
		return (M)this;
	}
	
	public java.lang.String getTimeOperate() {
		return getStr("time_operate");
	}
	
	public M setZjValue(java.lang.String zjValue) {
		set("zj_value", zjValue);
		return (M)this;
	}
	
	public java.lang.String getZjValue() {
		return getStr("zj_value");
	}
	
	public M setZjText(java.lang.String zjText) {
		set("zj_text", zjText);
		return (M)this;
	}
	
	public java.lang.String getZjText() {
		return getStr("zj_text");
	}
	
}

