package com.dsfa.platform.service.core.web.test.lsf.nc.szgl.model.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSzgl<M extends BaseSzgl<M>> extends DsfaBaseModel<M> implements IBean {

	public M setTestLsfNcSzglId(java.lang.String testLsfNcSzglId) {
		set("test_lsf_nc_szgl_id", testLsfNcSzglId);
		return (M)this;
	}
	
	public java.lang.String getTestLsfNcSzglId() {
		return getStr("test_lsf_nc_szgl_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setIsFamousValue(java.lang.String isFamousValue) {
		set("is_famous_value", isFamousValue);
		return (M)this;
	}
	
	public java.lang.String getIsFamousValue() {
		return getStr("is_famous_value");
	}
	
	public M setIsFamousText(java.lang.String isFamousText) {
		set("is_famous_text", isFamousText);
		return (M)this;
	}
	
	public java.lang.String getIsFamousText() {
		return getStr("is_famous_text");
	}
	
	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public M setTimeCjgz(java.util.Date timeCjgz) {
		set("time_cjgz", timeCjgz);
		return (M)this;
	}
	
	public java.util.Date getTimeCjgz() {
		return getDate("time_cjgz");
	}
	
	public M setDw(java.lang.String dw) {
		set("dw", dw);
		return (M)this;
	}
	
	public java.lang.String getDw() {
		return getStr("dw");
	}
	
	public M setZyzw(java.lang.String zyzw) {
		set("zyzw", zyzw);
		return (M)this;
	}
	
	public java.lang.String getZyzw() {
		return getStr("zyzw");
	}
	
	public M setTimeBirth(java.util.Date timeBirth) {
		set("time_birth", timeBirth);
		return (M)this;
	}
	
	public java.util.Date getTimeBirth() {
		return getDate("time_birth");
	}
	
	public M setJgValue(java.lang.String jgValue) {
		set("jg_value", jgValue);
		return (M)this;
	}
	
	public java.lang.String getJgValue() {
		return getStr("jg_value");
	}
	
	public M setJgText(java.lang.String jgText) {
		set("jg_text", jgText);
		return (M)this;
	}
	
	public java.lang.String getJgText() {
		return getStr("jg_text");
	}
	
	public M setZw(java.lang.String zw) {
		set("zw", zw);
		return (M)this;
	}
	
	public java.lang.String getZw() {
		return getStr("zw");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setSexValue(java.lang.String sexValue) {
		set("sex_value", sexValue);
		return (M)this;
	}
	
	public java.lang.String getSexValue() {
		return getStr("sex_value");
	}
	
	public M setSexText(java.lang.String sexText) {
		set("sex_text", sexText);
		return (M)this;
	}
	
	public java.lang.String getSexText() {
		return getStr("sex_text");
	}
	
	public M setPxm(java.lang.String pxm) {
		set("pxm", pxm);
		return (M)this;
	}
	
	public java.lang.String getPxm() {
		return getStr("pxm");
	}
	
	public M setStatusTopValue(java.lang.String statusTopValue) {
		set("status_top_value", statusTopValue);
		return (M)this;
	}
	
	public java.lang.String getStatusTopValue() {
		return getStr("status_top_value");
	}
	
	public M setStatusTopText(java.lang.String statusTopText) {
		set("status_top_text", statusTopText);
		return (M)this;
	}
	
	public java.lang.String getStatusTopText() {
		return getStr("status_top_text");
	}
	
	public M setZytc(java.lang.String zytc) {
		set("zytc", zytc);
		return (M)this;
	}
	
	public java.lang.String getZytc() {
		return getStr("zytc");
	}
	
	public M setHealth(java.lang.String health) {
		set("health", health);
		return (M)this;
	}
	
	public java.lang.String getHealth() {
		return getStr("health");
	}
	
	public M setMzValue(java.lang.String mzValue) {
		set("mz_value", mzValue);
		return (M)this;
	}
	
	public java.lang.String getMzValue() {
		return getStr("mz_value");
	}
	
	public M setMzText(java.lang.String mzText) {
		set("mz_text", mzText);
		return (M)this;
	}
	
	public java.lang.String getMzText() {
		return getStr("mz_text");
	}
	
	public M setMobieImg(java.lang.String mobieImg) {
		set("mobie_img", mobieImg);
		return (M)this;
	}
	
	public java.lang.String getMobieImg() {
		return getStr("mobie_img");
	}
	
	public M setTimeRd(java.util.Date timeRd) {
		set("time_rd", timeRd);
		return (M)this;
	}
	
	public java.util.Date getTimeRd() {
		return getDate("time_rd");
	}
	
	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}
	
	public M setTagValue(java.lang.String tagValue) {
		set("tag_value", tagValue);
		return (M)this;
	}
	
	public java.lang.String getTagValue() {
		return getStr("tag_value");
	}
	
	public M setTagText(java.lang.String tagText) {
		set("tag_text", tagText);
		return (M)this;
	}
	
	public java.lang.String getTagText() {
		return getStr("tag_text");
	}
	
	public M setStatusValue(java.lang.String statusValue) {
		set("status_value", statusValue);
		return (M)this;
	}
	
	public java.lang.String getStatusValue() {
		return getStr("status_value");
	}
	
	public M setStatusText(java.lang.String statusText) {
		set("status_text", statusText);
		return (M)this;
	}
	
	public java.lang.String getStatusText() {
		return getStr("status_text");
	}
	
	public M setPcImg(java.lang.String pcImg) {
		set("pc_img", pcImg);
		return (M)this;
	}
	
	public java.lang.String getPcImg() {
		return getStr("pc_img");
	}
	
	public M setTypeValue(java.lang.String typeValue) {
		set("type_value", typeValue);
		return (M)this;
	}
	
	public java.lang.String getTypeValue() {
		return getStr("type_value");
	}
	
	public M setTypeText(java.lang.String typeText) {
		set("type_text", typeText);
		return (M)this;
	}
	
	public java.lang.String getTypeText() {
		return getStr("type_text");
	}
	
	public M setIntro(java.lang.String intro) {
		set("intro", intro);
		return (M)this;
	}
	
	public java.lang.String getIntro() {
		return getStr("intro");
	}
	
	public M setSn(java.lang.String sn) {
		set("sn", sn);
		return (M)this;
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}
	
	public M setBirthArea(java.lang.String birthArea) {
		set("birth_area", birthArea);
		return (M)this;
	}
	
	public java.lang.String getBirthArea() {
		return getStr("birth_area");
	}
	
	public M setNumOfPublishLesson(java.lang.String numOfPublishLesson) {
		set("num_of_publish_lesson", numOfPublishLesson);
		return (M)this;
	}
	
	public java.lang.String getNumOfPublishLesson() {
		return getStr("num_of_publish_lesson");
	}
	
	public M setNumOfLeasson(java.lang.String numOfLeasson) {
		set("num_of_leasson", numOfLeasson);
		return (M)this;
	}
	
	public java.lang.String getNumOfLeasson() {
		return getStr("num_of_leasson");
	}
	
	public M setZj(java.lang.String zj) {
		set("zj", zj);
		return (M)this;
	}
	
	public java.lang.String getZj() {
		return getStr("zj");
	}
	
	public M setZc(java.lang.String zc) {
		set("zc", zc);
		return (M)this;
	}
	
	public java.lang.String getZc() {
		return getStr("zc");
	}
	
	public M setGzdw(java.lang.String gzdw) {
		set("gzdw", gzdw);
		return (M)this;
	}
	
	public java.lang.String getGzdw() {
		return getStr("gzdw");
	}
	
}

