package com.dsfa.platform.service.core.web.test.lsf.nc.kjgl.model;

import com.dsfa.platform.service.core.web.test.lsf.nc.kjgl.model.base.BaseKjk;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

import java.io.Serializable;

/**
 * Generated by JFinal.
 */
@TableBind(
		tableName = "test_lsf_nc_kjk",
		pkName = "test_lsf_nc_kjk_id"
)
public class Kjk extends BaseKjk<Kjk> implements Serializable {
	public static final Kjk dao = new Kjk().dao();

	public Kjk() {
	}
}

