package com.dsfa.platform.service.core.web.test.lsf.nc.kjgl.model;

import com.dsfa.platform.service.core.web.test.lsf.nc.kjgl.model.base.BaseKjkTeachers;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(
		tableName = "test_lsf_nc_kjk_teachers",
		pkName = "test_lsf_nc_kjk_teachers_id"
)
public class KjkTeachers extends BaseKjkTeachers<KjkTeachers> {
	public static final KjkTeachers dao = new KjkTeachers().dao();

	public KjkTeachers() {
	}
}

