package com.dsfa.platform.service.core.web.test.lsf.nc.kjgl.model.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKjk<M extends BaseKjk<M>> extends DsfaBaseModel<M> implements IBean {

	public M setTestLsfNcKjkId(java.lang.String testLsfNcKjkId) {
		set("test_lsf_nc_kjk_id", testLsfNcKjkId);
		return (M)this;
	}
	
	public java.lang.String getTestLsfNcKjkId() {
		return getStr("test_lsf_nc_kjk_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setVideoFile(java.lang.String videoFile) {
		set("video_file", videoFile);
		return (M)this;
	}
	
	public java.lang.String getVideoFile() {
		return getStr("video_file");
	}
	
	public M setVideoSize(java.lang.String videoSize) {
		set("video_size", videoSize);
		return (M)this;
	}
	
	public java.lang.String getVideoSize() {
		return getStr("video_size");
	}
	
	public M setTypeValue(java.lang.String typeValue) {
		set("type_value", typeValue);
		return (M)this;
	}
	
	public java.lang.String getTypeValue() {
		return getStr("type_value");
	}
	
	public M setTypeText(java.lang.String typeText) {
		set("type_text", typeText);
		return (M)this;
	}
	
	public java.lang.String getTypeText() {
		return getStr("type_text");
	}
	
	public M setCopyrightOwner(java.lang.String copyrightOwner) {
		set("copyright_owner", copyrightOwner);
		return (M)this;
	}
	
	public java.lang.String getCopyrightOwner() {
		return getStr("copyright_owner");
	}
	
	public M setZddw(java.lang.String zddw) {
		set("zddw", zddw);
		return (M)this;
	}
	
	public java.lang.String getZddw() {
		return getStr("zddw");
	}
	
	public M setSn(java.lang.String sn) {
		set("sn", sn);
		return (M)this;
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setVideoDuration(java.lang.String videoDuration) {
		set("video_duration", videoDuration);
		return (M)this;
	}
	
	public java.lang.String getVideoDuration() {
		return getStr("video_duration");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setDocumentFile(java.lang.String documentFile) {
		set("document_file", documentFile);
		return (M)this;
	}
	
	public java.lang.String getDocumentFile() {
		return getStr("document_file");
	}
	
	public M setTgdw(java.lang.String tgdw) {
		set("tgdw", tgdw);
		return (M)this;
	}
	
	public java.lang.String getTgdw() {
		return getStr("tgdw");
	}
	
	public M setEnabledStatusValue(java.lang.String enabledStatusValue) {
		set("enabled_status_value", enabledStatusValue);
		return (M)this;
	}
	
	public java.lang.String getEnabledStatusValue() {
		return getStr("enabled_status_value");
	}
	
	public M setEnabledStatusText(java.lang.String enabledStatusText) {
		set("enabled_status_text", enabledStatusText);
		return (M)this;
	}
	
	public java.lang.String getEnabledStatusText() {
		return getStr("enabled_status_text");
	}
	
	public M setAudioFile(java.lang.String audioFile) {
		set("audio_file", audioFile);
		return (M)this;
	}
	
	public java.lang.String getAudioFile() {
		return getStr("audio_file");
	}
	
	public M setPcAddress(java.lang.String pcAddress) {
		set("pc_address", pcAddress);
		return (M)this;
	}
	
	public java.lang.String getPcAddress() {
		return getStr("pc_address");
	}
	
	public M setMobieAddress(java.lang.String mobieAddress) {
		set("mobie_address", mobieAddress);
		return (M)this;
	}
	
	public java.lang.String getMobieAddress() {
		return getStr("mobie_address");
	}
	
}

