package com.dsfa.platform.service.core.web.test.lsf.nc.kjgl.model.base;

import com.dsfa.platform.starter.meta.base.DsfaBaseModel;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKjkTeachers<M extends BaseKjkTeachers<M>> extends DsfaBaseModel<M> implements IBean {

	public M setTestLsfNcKjkTeachersId(java.lang.String testLsfNcKjkTeachersId) {
		set("test_lsf_nc_kjk_teachers_id", testLsfNcKjkTeachersId);
		return (M)this;
	}
	
	public java.lang.String getTestLsfNcKjkTeachersId() {
		return getStr("test_lsf_nc_kjk_teachers_id");
	}
	
	public M setDsUpdateUserId(java.lang.String dsUpdateUserId) {
		set("ds_update_user_id", dsUpdateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserId() {
		return getStr("ds_update_user_id");
	}
	
	public M setDsDeptId(java.lang.String dsDeptId) {
		set("ds_dept_id", dsDeptId);
		return (M)this;
	}
	
	public java.lang.String getDsDeptId() {
		return getStr("ds_dept_id");
	}
	
	public M setDsCreateUserName(java.lang.String dsCreateUserName) {
		set("ds_create_user_name", dsCreateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserName() {
		return getStr("ds_create_user_name");
	}
	
	public M setDsCreateUserId(java.lang.String dsCreateUserId) {
		set("ds_create_user_id", dsCreateUserId);
		return (M)this;
	}
	
	public java.lang.String getDsCreateUserId() {
		return getStr("ds_create_user_id");
	}
	
	public M setDsUpdateUserName(java.lang.String dsUpdateUserName) {
		set("ds_update_user_name", dsUpdateUserName);
		return (M)this;
	}
	
	public java.lang.String getDsUpdateUserName() {
		return getStr("ds_update_user_name");
	}
	
	public M setDsDeleted(java.lang.String dsDeleted) {
		set("ds_deleted", dsDeleted);
		return (M)this;
	}
	
	public java.lang.String getDsDeleted() {
		return getStr("ds_deleted");
	}
	
	public M setDsOrder(java.lang.Integer dsOrder) {
		set("ds_order", dsOrder);
		return (M)this;
	}
	
	public java.lang.Integer getDsOrder() {
		return getInt("ds_order");
	}
	
	public M setDsUnitId(java.lang.String dsUnitId) {
		set("ds_unit_id", dsUnitId);
		return (M)this;
	}
	
	public java.lang.String getDsUnitId() {
		return getStr("ds_unit_id");
	}
	
	public M setDsCreateTime(java.util.Date dsCreateTime) {
		set("ds_create_time", dsCreateTime);
		return (M)this;
	}
	
	public java.util.Date getDsCreateTime() {
		return getDate("ds_create_time");
	}
	
	public M setDsUpdateTime(java.util.Date dsUpdateTime) {
		set("ds_update_time", dsUpdateTime);
		return (M)this;
	}
	
	public java.util.Date getDsUpdateTime() {
		return getDate("ds_update_time");
	}
	
	public M setTestLsfNcKjkId(java.lang.String testLsfNcKjkId) {
		set("test_lsf_nc_kjk_id", testLsfNcKjkId);
		return (M)this;
	}
	
	public java.lang.String getTestLsfNcKjkId() {
		return getStr("test_lsf_nc_kjk_id");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setDw(java.lang.String dw) {
		set("dw", dw);
		return (M)this;
	}
	
	public java.lang.String getDw() {
		return getStr("dw");
	}
	
	public M setZcValue(java.lang.String zcValue) {
		set("zc_value", zcValue);
		return (M)this;
	}
	
	public java.lang.String getZcValue() {
		return getStr("zc_value");
	}
	
	public M setZcText(java.lang.String zcText) {
		set("zc_text", zcText);
		return (M)this;
	}
	
	public java.lang.String getZcText() {
		return getStr("zc_text");
	}
	
	public M setGzdw(java.lang.String gzdw) {
		set("gzdw", gzdw);
		return (M)this;
	}
	
	public java.lang.String getGzdw() {
		return getStr("gzdw");
	}
	
	public M setZjValue(java.lang.String zjValue) {
		set("zj_value", zjValue);
		return (M)this;
	}
	
	public java.lang.String getZjValue() {
		return getStr("zj_value");
	}
	
	public M setZjText(java.lang.String zjText) {
		set("zj_text", zjText);
		return (M)this;
	}
	
	public java.lang.String getZjText() {
		return getStr("zj_text");
	}
	
	public M setZwValue(java.lang.String zwValue) {
		set("zw_value", zwValue);
		return (M)this;
	}
	
	public java.lang.String getZwValue() {
		return getStr("zw_value");
	}
	
	public M setZwText(java.lang.String zwText) {
		set("zw_text", zwText);
		return (M)this;
	}
	
	public java.lang.String getZwText() {
		return getStr("zw_text");
	}
	
	public M setTeacherId(java.lang.String teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}
	
	public java.lang.String getTeacherId() {
		return getStr("teacher_id");
	}
	
}

