package com.dsfa.platform.service.core.web.test.lsf.nc.szgl.model;

import com.dsfa.platform.service.core.web.test.lsf.nc.szgl.model.base.BaseSzglXljy;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(
		tableName = "test_lsf_nc_szgl_xljy",
		pkName = "test_lsf_nc_szgl_xljy_id"
)
public class SzglXljy extends BaseSzglXljy<SzglXljy> {
	public static final SzglXljy dao = new SzglXljy().dao();
}

