package com.dsfa.platform.service.core.web.test.lsf.nc.szgl.model;

import com.dsfa.platform.service.core.web.test.lsf.nc.szgl.model.base.BaseSzgl;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(
		tableName = "test_lsf_nc_szgl",
		pkName = "test_lsf_nc_szgl_id"
)
public class Szgl extends BaseSzgl<Szgl> {
	public static final Szgl dao = new Szgl().dao();
}

