package com.dsfa.platform.service.core.web.test.lsf.nc.szgl.model;

import com.dsfa.platform.service.core.web.test.lsf.nc.szgl.model.base.BaseSzglBdxx;
import com.dsfa.platform.starter.db.jfinal.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(
		tableName = "test_lsf_nc_szgl_bdxx",
		pkName = "test_lsf_nc_szgl_bdxx_id"
)
public class SzglBdxx extends BaseSzglBdxx<SzglBdxx> {
	public static final SzglBdxx dao = new SzglBdxx().dao();
}

